### ISSUE TITLE
Where and what is the module 'dt'? 

### ISSUE THREAD

**Issue by MingwuZheng** [weders/graphics#1]
when I import your module I met this error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
 File "~/anaconda3/envs/routed-fusion/lib/python3.7/site-packages/graphics-0.1.dev0-py3.7.egg/graphics/__init__.py", line 1, in <module>
File "~/anaconda3/envs/routed-fusion/lib/python3.7/site-packages/graphics-0.1.dev0-py3.7.egg/graphics/voxelgrid.py", line 4, in <module>
File "~/anaconda3/envs/routed-fusion/lib/python3.7/site-packages/graphics-0.1.dev0-py3.7.egg/graphics/transform.py", line 2, in <module>
ModuleNotFoundError: No module named 'dt'`
What does it mean and where can I find this module? Hope for your reply, much thanks!

**Comment by weders** [comment]
This is this library (it's a fork): https://github.com/weders/distance-transform/

Did you initialize and install all submodules in the deps folder? This should resolve your issue.

**Comment by MingwuZheng** [comment]
It works. Thanks for your quick reply!
